-- MySQL Script generated by MySQL Workbench
-- Fri Oct  4 18:49:40 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema GerenciadorTarefas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema GerenciadorTarefas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `GerenciadorTarefas` DEFAULT CHARACTER SET utf8 ;
USE `GerenciadorTarefas` ;

-- -----------------------------------------------------
-- Table `GerenciadorTarefas`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GerenciadorTarefas`.`Usuario` (
  `emailUsuario` VARCHAR(60) NOT NULL,
  `nomeUsuario` VARCHAR(100) NOT NULL,
  `senhaUsuario` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`emailUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GerenciadorTarefas`.`projeto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GerenciadorTarefas`.`projeto` (
  `idProjeto` INT NOT NULL,
  `descProjeto` VARCHAR(100) NULL,
  `usuarioEmailUsuario` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idProjeto`),
  INDEX `fk_Projeto_Usuario1_idx` (`usuarioEmailUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Projeto_Usuario1`
    FOREIGN KEY (`usuarioEmailUsuario`)
    REFERENCES `GerenciadorTarefas`.`Usuario` (`emailUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GerenciadorTarefas`.`tarefa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GerenciadorTarefas`.`tarefa` (
  `idTarefa` INT NOT NULL,
  `descTarefa` VARCHAR(200) NULL,
  `dataAgendada` TIMESTAMP NULL,
  `isFinalizada` TINYINT(1) NULL,
  `prioridade` ENUM('PRIORIDADE1', 'PRIORIDADE2', 'PRIORIDADE3', 'PRIORIDADE4') NULL DEFAULT 'Prioridade1',
  `projetoIdProjeto` INT NOT NULL,
  PRIMARY KEY (`idTarefa`),
  INDEX `fk_Tarefas_Projeto_idx` (`projetoIdProjeto` ASC) VISIBLE,
  CONSTRAINT `fk_Tarefas_Projeto`
    FOREIGN KEY (`projetoIdProjeto`)
    REFERENCES `GerenciadorTarefas`.`projeto` (`idProjeto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
